# Change these first
owner: hophuochoanggia
repo: upptime

sites:
  - name: DeLonghi Vietnam
    url: https://delonghi.vn
  - name: DeLonghi Thailand
    url: https://delonghi.co.th
  - name: DeLonghi Cambodia
    url: https://kh.delonghi.com
  - name: DeLonghi Indonesia
    url: https://id.delonghi.com
  - name: Braun Household Thailand
    url: https://th.braunhousehold.com
  - name: Braun Household Vietnam
    url: https://vn.braunhousehold.com
  - name: Kenwood Thailand
    url: https://th.kenwoodworld.com
  - name: NutriBullet Singapore
    url: https://nutribullet.sg
  - name: Eurocham VN
    url: https://eurochamvn.org/
  - name: Eurocham CA
    url: https://eurocham-cambodia.org/
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

schedule:
  - cron: "*/30 * * * *"


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
